

window.langClever = {
	lang:	{
		'ru': {
			'title': 'Пульт оператора',
			'enter': 'Войти',
			'loadintEnter': 'Выполняется вход на сервер...',
			'cancel': 'Отмена',
			'save': 'Сохранить',
			'write': 'печатает',
			'hour': 'ч',
			'minutes': 'м',
			'xmpp_error': {
				'loginOrPass': 'Неправильные имя или пароль',
				'replace': 'Было подключение с другого устройства',
				'limit': 'Превышен максимально допустимый лимит операторов онлайн',
				'block1': 'Ваша учетная запись заблокирована',
				'block2': 'Ваша учетная запись заблокирована',
				'dataPay1': 'Закончилась дата оплаты',
				'dataPay2': 'Закончилась дата оплаты',
				'connect': 'Разрыв интернет соединения',
				'noServer': 'Сервер не отвечает',
			},
			'user_info_top': {
				'visits': 'Визитов: ',
				'countPage': ', Просмотренных страниц: ',
			},
			'notify': {
				'newDialog': 'Новый диалог',
				'newMessage': 'Новое сообщение',
				'redirect': 'Перевод диалога',
				'redirectOper': 'От оператора:',
				'redirectClient': 'От клиента:',
				'redirectSelect': 'Выбирете оператора, для передачи диалога',
				'noIgnore': 'Вы не можете игнорировать этот диалог, т.к. вы единственный оставшийся оператор',
				'chat': 'К чату',
				'close': 'Закрыть',
				'cancel': 'Отменить',
				'send': 'Послать',
				'accept': 'Принять',
				'redirecting': 'Передать',
				'noOper': 'Операторы отсутствуют',
				'redirectSuccess': 'Диалог успешно переведен',
				'redirectReject': 'Перевод диалога отклонен',
				'block': 'Блокировка клиента',
				'blockSuccess': 'Блокировка завершена',
				'sendEmail': 'Отправить диалог с клиентом',
				'email': 'Email',
				'note': 'Примечание к письму',
				'sendSuccess': 'Успешно отправлено',
				'errorUpload': 'Ошибка загрузки файла',
				'whatAct': 'Выберите действие, которое необходимо сделать с диалогом',
				'threadClose': 'Диалог закрыт',
				'sait': 'Сайт:',
				'client': 'Клиент:',
				'reject': 'Отклонить',
				'answer': 'Ответить',
				'answerFast': 'Быстрый ответ',
				'ignore': 'Игнорировать',
				'comment': 'Комментарий',
				'resirectReject': 'Запрос на перевод отменен',
				'versionOld': 'Версия приложения устарела',
				'versionOld_text': 'Вам необходимо перезапуститься в ближайшее время, для стабильной работы приложения',
				'restart': 'Перезапустить',
				'goAway': 'Переход в AWAY',
				'goAwayText': 'Для перехода в AWAY необходимо закрыть все активные диалоги',
				'uploadErrorType': 'Неверный тип загружаемого',
				'uploadErrorSize': 'Превышен размер файла. Зугражаемый',
				'uploadErrorSizeLimit': 'Mb. Лимит - 2 Mb.',
				'fastAnswerPlaceholder': 'Введите текст ответа',
			},
			'user_info': {
				'browser': 'Браузер',
				'ip': 'IP-адрес',
				'visits': 'Визитов',
				'dialogs': 'Диалогов',
				'watch': 'Смотрит',
				'istok': 'Источник',
				'history': 'История посещений:',
			},
			'top_menu': {
				'transfer': 'Передать диалог',
				'block': 'Блокировать',
				'send_email': 'Отправить на почту',
				'visitors': 'Посетители',
				'operators': 'Операторы',
				'clients': 'Клиенты',
				'property': 'Настройки',
				'exit': 'Выход',
			},
			'content_info': 'В этом окне вы сможете общаться с посетителями сайта, которые напишут онлайн-консультанту',
			'history': 'История',
			'msgwnd_placeholder': 'Напишите ваше сообщение',
			'property': {
				'menu': {
					'status': 'Статус',
					'phrases': 'Фразы',
					'lang': 'Язык',
					'notify': 'Оповещения',
					'autostart': 'Автозапуск',
					'spelling': 'Орфография',
					'visual': 'Внешний вид',
					'report': 'Отчёты',
					'about': 'О программе',
				},
				'prop_status': {
					'text': 'Время бездействия пользователя<br/>до изменения статуса, минуты:',
					'never': 'Никогда',
					'closetext': 'Закрывать открытые диалоги с клиентами<br/>при изменении статуса',
				},
				'prop_phrase': {
					'placeholder': 'Введите текст быстрого сообщения, и нажмите добавить',
					'def': [
						'Привет! Я могу помочь?',
						'Здравствуйте! Я могу Вам помочь?', 
						'Обращайтесь, если понадобится помощь:)'
					]
				},
				'prop_lang': {
					'prop_lang_rus': 'Русский',
					'prop_lang_en': 'Английский',
				},
				'prop_sound': {
					'enable': 'Использовать звуковые оповещения о событиях',
					'textForClient': 'Сообщения от клиента',
					'textForOperator': 'Сообщения от оператора',
					'no': 'Нет (без звука)',
					'noty1': 'Нотификация 1',
					'noty2': 'Нотификация 2',
				},
				'prop_autostart': {
					'prop_autoStart': 'Запускать автоматически',
					'prop_autoIn': 'Входить автоматически',
				},
				'prop_report': {
					'prop_sendReport': 'Отправлять отчеты об ошибках',
					'text': 'Автоматически отправлять отчеты об ошибках в приложении разработчикам компании Cleversite',
				},
				'prop_about': {
					'text': 'Версия приложения: ',
				},
			}
		},
		

		
		
		'en': {
			'title': 'ClientManager',
			'enter': 'Enter',
			'loadintEnter': 'Logging in to the server ...',
			'cancel': 'cancel',
			'save': 'Save',
			'write': 'Write',
			'hour': 'h',
			'minutes': 'm',
			'xmpp_error': {
				'loginOrPass': 'Wrong username or password',
				'replace': 'It was a connection with another device',
				'limit': 'Exceeded the maximum allowable limit of operators of online',
				'block1': 'Your account is locked out',
				'block2': 'Your account is locked out',
				'dataPay1': 'Ended payment date',
				'dataPay2': 'Ended payment date',
				'connect': 'Break the Internet connection',
				'noServer': 'The server is not responding',
			},
			'user_info_top': {
				'visits': 'Visits: ',
				'countPage': ', Page views: ',
			},
			'notify': {
				'newDialog': 'New dialogue',
				'newMessage': 'New message',
				'redirect': 'Translation of dialogue',
				'redirectOper': 'The operator:',
				'redirectClient': 'The clients:',
				'redirectSelect': 'Choose the operator for the transfer dialogue',
				'noIgnore': 'You can not ignore this dialogue, because you are the only remaining operator',
				'chat': 'To chat',
				'close': 'Close',
				'cancel': 'Cancel',
				'send': 'Send',
				'accept': 'Accept',
				'redirecting': 'Send',
				'noOper': 'No operators',
				'redirectSuccess': 'Conversation successfully transferred',
				'redirectReject': 'Translation of dialogue rejected',
				'block': 'Lock the client',
				'blockSuccess': 'Lock completed',
				'sendEmail': 'Send a dialogue with the customer',
				'email': 'Email',
				'note': 'Note to the letter',
				'sendSuccess': 'Successfully sent',
				'errorUpload': 'Upload error',
				'whatAct': 'Select the action that needs to be done with the dialogue',
				'threadClose': 'Dialogue is closed',
				'sait': 'Website:',
				'client': 'Client:',
				'reject': 'Reject',
				'answer': 'Reply',
				'answerFast': 'Quick Reply',
				'ignore': 'Ignore',
				'comment': 'Comment',
				'resirectReject': 'The transfer request shall be canceled',
				'versionOld': 'App version is outdatedа',
				'versionOld_text': 'You need to be restarted in the near future, for the stable operation of the application',
				'restart': 'Restart',
				'goAway': 'Go to the AWAY',
				'goAwayText': 'it is necessary to close all active dialogs to move in AWAY',
				'uploadErrorType': 'Wrong type feed',
				'uploadErrorSize': 'xceeded file size. ',
				'uploadErrorSizeLimit': 'Mb. Limit - 2 Mb',
				'fastAnswerPlaceholder': 'Send answer',
			},
			'user_info': {
				'browser': 'Икщцыук',
				'ip': 'IP',
				'visits': 'Visits',
				'dialogs': 'Dialogues',
				'watch': 'Watch',
				'istok': 'Istok',
				'history': 'History:',
			},
			'top_menu': {
				'transfer': 'Transfer dialog',
				'block': 'Block',
				'send_email': 'Send email',
				'visitors': 'Visitors',
				'operators': 'Operators',
				'clients': 'Clients',
				'property': 'Property',
				'exit': 'Exit',
			},
			'content_info': 'In this window you will be able to communicate with site visitors who write online consultant',
			'history': 'History',
			'msgwnd_placeholder': 'Write your message',
			'property': {
				'menu': {
					'status': 'Status',
					'phrases': 'Phrases',
					'lang': 'Lang',
					'notify': 'Notifications',
					'autostart': 'Autostart',
					'spelling': 'Spelling',
					'visual': 'Visual',
					'report': 'Report',
					'about': 'About',
				},
				'prop_status': {
					'text': 'Time without user <br/> to change the status of minutes:',
					'never': 'Never',
					'closetext': 'Close the open dialogs with customers <br/> status change',
				},
				'prop_phrase': {
					'placeholder': 'Enter a flash message , and then click Add',
					'def': [
						'Hi! I can help?',
						'Hello! I can help you?', 
						'Ask if you need help :)'
					]
				},
				'prop_lang': {
					'prop_lang_rus': 'Русский',
					'prop_lang_en': 'English',
				},
				'prop_sound': {
					'enable': 'Use sound notifications about events',
					'textForClient': 'Messages from the client',
					'textForOperator': 'Messages from the operator',
					'no': 'No (no sound)',
					'noty1': 'Notification 1',
					'noty2': 'Notification 2',
				},
				'prop_autostart': {
					'prop_autoStart': 'Start automatically',
					'prop_autoIn': 'log in automatically',
				},
				'prop_report': {
					'prop_sendReport': 'Send crash reports',
					'text': 'Automatically send crash reports to developers of application Cleversite',
				},
				'prop_about': {
					'text': 'Version app: ',
				},
			}
		},
	}
}

			